# Generated by Django 3.2.4 on 2021-06-06 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_count', models.IntegerField(default=0)),
                ('click_power', models.IntegerField(default=1)),
                ('auto_click_power', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=0)),
                ('boost_type', models.IntegerField(default=0)),
                ('main_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mars.maincycle')),
            ],
        ),
    ]
